apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  selector:
    app: spring-boot-app
  type: LoadBalancer # GKE will provision a GCP load balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
